project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: Walker-bc

parameters:
  alg:
    value: bc 
  bc-num-epochs:
    value: 1000 
  bc-state-norm:
    value: True 
  clip-actions:
    value: True 
  cuda:
    value: True 
  env-name:
    value: Walker2d-v3 
  eval-interval:
    value: 1000 
  eval-num-processes:
    value: 10 
  log-interval:
    value: 200 
  lr:
    value: 0.0001 
  normalize-env:
    value: False 
  num-eval:
    value: 10 
  num-render:
    value: 0 
  prefix:
    value: bc 
  save-interval:
    value: 100000 
  traj-load-path:
    value: ./expert_datasets/walker_5traj_processed.pt 
  vid-fps:
    value: 100 
  seed:
    values: [1,2,3]