project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: Walker-ibc

parameters:
  alg:
    value: ibc 
  bc-num-epochs:
    value: 10000 
  bc-state-norm:
    value: True 
  clip-actions:
    value: True 
  cuda:
    value: True 
  depth:
    value: 1 
  env-name:
    value: Walker2d-v3 
  eval-interval:
    value: 4000 
  eval-num-processes:
    value: 10 
  hidden-dim:
    value: 1024 
  log-interval:
    value: 200 
  lr:
    value: 0.00008 
  normalize-env:
    value: False 
  num-eval:
    value: 3 
  num-render:
    value: 0 
  prefix:
    value: ibc 
  save-interval:
    value: 100000 
  traj-load-path:
    value: ./expert_datasets/walker_5traj_processed.pt 
  vid-fps:
    value: 100 
  seed:
    values: [1,2,3]