project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: Pick-dp-1.25

parameters:
  alg:
    value: dp 
  bc-num-epochs:
    value: 15000 
  bc-state-norm:
    value: True 
  clip-actions:
    value: True 
  cuda:
    value: True 
  depth:
    value: 4 
  env-name:
    value: FetchPickAndPlaceDiffHoldout-v0 
  eval-interval:
    value: 9000 
  eval-num-processes:
    value: 10 
  hidden-dim:
    value: 1200 
  log-interval:
    value: 3000 
  lr:
    value: 1e-05 
  normalize-env:
    value: False 
  num-eval:
    value: 10 
  num-render:
    value: 0 
  prefix:
    value: dp 
  save-interval:
    value: 500000 
  traj-batch-size:
    value: 128 
  traj-load-path:
    value: ./expert_datasets/pick_10000_clip.pt 
  vid-fps:
    value: 30 
  noise-ratio:
    value: 1.25 
  goal-noise-ratio:
    value: 1.25 
  seed:
    values: [1,2,3]