project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Hand-dp"

parameters:
  alg:
    value: dp 
  bc-num-epochs:
    value: 30000 
  bc-state-norm:
    value: True 
  clip-actions:
    value: True 
  cuda:
    value: True 
  env-name:
    value: CustomHandManipulateBlockRotateZ-v2 
  eval-interval:
    value: 20000 
  eval-num-processes:
    value: 10 
  log-interval:
    value: 2000 
  lr:
    value: 0.0001 
  normalize-env:
    value: False 
  num-eval:
    value: 10 
  num-render:
    value: 3 
  prefix:
    value: dp 
  save-interval:
    value: 100000 
  traj-load-path:
    value: ./expert_datasets/hand_10000_v2.pt 
  hidden-dim:
    value: 2100 
  dp-scheduler-type:
    value: sigmoid 
  vid-fps:
    value: 30 
  depth:
    value: 4 
  seed:
    values: [1,2,3] 