project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Hand-ibc"

parameters:
  alg:
    value: ibc 
  bc-num-epochs:
    value: 15000 
  bc-state-norm:
    value: True 
  clip-actions:
    value: True 
  cuda:
    value: True 
  depth:
    value: 1 
  env-name:
    value: CustomHandManipulateBlockRotateZ-v2 
  eval-interval:
    value: 3000 
  eval-num-processes:
    value: 10 
  hidden-dim:
    value: 512 
  log-interval:
    value: 1000 
  lr:
    value: 1e-05 
  normalize-env:
    value: False 
  num-eval:
    value: 10 
  num-process:
    value: 10 
  num-render:
    value: 0 
  prefix:
    value: ibc 
  save-interval:
    value: 500000 
  stochastic-optimizer-train_samples:
    value: 256 
  traj-batch-size:
    value: 512 
  traj-load-path:
    value: ./expert_datasets/hand_10000_v2.pt 
  seed:
    values: [1,2,3]