project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Maze-bc"

parameters:
  alg:
    value: bc
  env-name:
    value: maze2d-medium-v2 
  lr:
    value: 0.00005 
  traj-load-path:
    value: ./expert_datasets/maze.pt 
  seed:
    values: [1,2,3]