project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Maze-bc"

parameters:
  alg:
    value: bc 
  bc-num-epochs:
    value: 2000 
  bc-state-norm:
    value: False 
  clip-actions:
    value: True 
  coeff:
    value: 0 
  coeff-bc:
    value: 1 
  cuda:
    value: True 
  depth:
    value: 3 
  env-name:
    value: maze2d-medium-v2 
  eval-interval:
    value: 2000 
  eval-num-processes:
    value: 1 
  hidden-dim:
    value: 256 
  il-in-action-norm:
    value: False 
  il-out-action-norm:
    value: False 
  log-interval:
    value: 200 
  lr:
    value: 0.00005 
  normalize-env:
    value: False 
  num-eval:
    value: 100 
  num-render:
    value: 3 
  save-interval:
    value: 20000 
  traj-load-path:
    value: ./expert_datasets/maze2d_100.pt 
  vid-fps:
    value: 60 
  log-diff-loss:
    value: True 
  prefix:
    value: bc-100 
  ddpm-path:
    value: ./rl-toolkit/dm/trained_models/maze2d_100_ddpm_0.0001_128_sigmoid_norm.pt 
  bc-state-norm:
    value: True 
  il-in-action-norm:
    value: True 
  il-out-action-norm:
    value: True 
  seed:
    values: [1,2,3]