project: 'dbc-reproduce'
program: dbc/main.py
method: grid
name: "Maze-ibc"

parameters:
  alg:
    value: ibc 
  bc-num-epochs:
    value: 10000 
  bc-state-norm:
    value: False 
  clip-actions:
    value: True 
  coeff:
    value: 0 
  coeff-bc:
    value: 1 
  cuda:
    value: True 
  depth:
    value: 1 
  env-name:
    value: maze2d-medium-v2 
  eval-interval:
    value: 15000 
  eval-num-processes:
    value: 10 
  hidden-dim:
    value: 1024 
  il-in-action-norm:
    value: False 
  il-out-action-norm:
    value: False 
  log-interval:
    value: 1000 
  lr:
    value: 0.0001 
  normalize-env:
    value: False 
  num-eval:
    value: 10 
  num-render:
    value: 0 
  prefix:
    value: ibc 
  save-interval:
    value: 500000 
  traj-load-path:
    value: ./expert_datasets/maze2d_100.pt 
  vid-fps:
    value: 60 
  seed:
    values: [1,2,3]